services:
  minio:
    image: "minio/minio:latest"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: "admin1234"
      MINIO_ROOT_PASSWORD: "admin1234"
    volumes:
      - "minio:/data/minio"
    command: minio server /data/minio --console-address ":9090"
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "personal"
    ports:
      - "5432:5432"
    volumes:
      - "postgres-personal:/var/lib/postgresql/data"
  redis:
    image: "redis:latest"
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_USER=admin1
      - REDIS_USER_PASSWORD=admin1
    ports:
      - "6380:6379"
    volumes:
      - "redis:/data"
      

volumes:
  minio:
    driver: local
  postgres-personal:
    driver: local
  redis:
    driver: local
